metamorphic: error out if flags are used incorrectly
The metamorphic test has some flags specific to the "outer" Run, and
some flags specific to `--run-dir/--compare`. If a flag is passed that
doesn't apply to the mode, it is ignored.

In this change we instead error out the test. This will reduce sources
of confusion, especially when trying to run things manually.

Examples:
```
--- FAIL: TestMeta (0.00s)
    meta_test.go:96: flag "previous-ops" is not allowed with --run-dir

--- FAIL: TestMeta (0.00s)
    meta_test.go:118: flag "try-to-reduce" is only allowed with --compare or --run-dir
```

Fixes #4845